pipeline{
    agent any
    stages{
        stage('uptime'){
            steps{
                sh '''
                uptime
                '''
            }
        }
        stage('Ram-Used'){
            steps{
                sh '''
                free -h
                '''
            }
        }
        stage('Disk-Used'){
            steps{
                sh '''
                df -kh
                '''
            }
        }
    }
}